// Mocks generated by Mockito 5.4.4 from annotations
// in magic_pay_app/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i11;
import 'package:magic_pay_app/core/error/failure.dart' as _i14;
import 'package:magic_pay_app/core/response_data.dart' as _i3;
import 'package:magic_pay_app/features/auth/data/data_sources/remote_data_source.dart'
    as _i30;
import 'package:magic_pay_app/features/auth/data/models/user.dart' as _i31;
import 'package:magic_pay_app/features/auth/domain/entities/user.dart' as _i15;
import 'package:magic_pay_app/features/auth/domain/repositories/auth_repositor.dart'
    as _i12;
import 'package:magic_pay_app/features/auth/domain/usecases/login.dart' as _i40;
import 'package:magic_pay_app/features/auth/domain/usecases/logout.dart'
    as _i41;
import 'package:magic_pay_app/features/auth/domain/usecases/register.dart'
    as _i42;
import 'package:magic_pay_app/features/home/data/data_sources/remote_data_source.dart'
    as _i32;
import 'package:magic_pay_app/features/home/domain/repositories/home_repository.dart'
    as _i16;
import 'package:magic_pay_app/features/home/domain/usecases/get_profile.dart'
    as _i43;
import 'package:magic_pay_app/features/home/domain/usecases/update_password.dart'
    as _i44;
import 'package:magic_pay_app/features/notification/data/data_sources/remote_data_source.dart'
    as _i33;
import 'package:magic_pay_app/features/notification/data/models/notification_data_model.dart'
    as _i4;
import 'package:magic_pay_app/features/notification/data/models/notification_detail_model.dart'
    as _i5;
import 'package:magic_pay_app/features/notification/domain/entities/notification_data.dart'
    as _i18;
import 'package:magic_pay_app/features/notification/domain/entities/notification_detail.dart'
    as _i19;
import 'package:magic_pay_app/features/notification/domain/repositories/notification_repositor.dart'
    as _i17;
import 'package:magic_pay_app/features/notification/domain/usecases/get_notification_detail.dart'
    as _i46;
import 'package:magic_pay_app/features/notification/domain/usecases/get_notifications.dart'
    as _i45;
import 'package:magic_pay_app/features/scan_pay/data/datasources/remote_data_source.dart'
    as _i38;
import 'package:magic_pay_app/features/scan_pay/data/models/scan_pay_data_model.dart'
    as _i10;
import 'package:magic_pay_app/features/scan_pay/data/models/scan_pay_form_data_model.dart'
    as _i9;
import 'package:magic_pay_app/features/scan_pay/data/models/scan_pay_request_model.dart'
    as _i39;
import 'package:magic_pay_app/features/scan_pay/domain/entities/scan_pay_data.dart'
    as _i28;
import 'package:magic_pay_app/features/scan_pay/domain/entities/scan_pay_form_data.dart'
    as _i27;
import 'package:magic_pay_app/features/scan_pay/domain/entities/scan_pay_request.dart'
    as _i29;
import 'package:magic_pay_app/features/scan_pay/domain/repositories/scan_pay_repository.dart'
    as _i26;
import 'package:magic_pay_app/features/transaction/data/data_sources/remote_data_source.dart'
    as _i34;
import 'package:magic_pay_app/features/transaction/data/models/transaction_detail_model.dart'
    as _i7;
import 'package:magic_pay_app/features/transaction/data/models/transactions_data_model.dart'
    as _i6;
import 'package:magic_pay_app/features/transaction/domain/entities/transaction_detail.dart'
    as _i22;
import 'package:magic_pay_app/features/transaction/domain/entities/transactions_data.dart'
    as _i21;
import 'package:magic_pay_app/features/transaction/domain/repositories/transaction_repository.dart'
    as _i20;
import 'package:magic_pay_app/features/transaction/domain/usecases/get_transaction_detail.dart'
    as _i48;
import 'package:magic_pay_app/features/transaction/domain/usecases/get_transactions.dart'
    as _i47;
import 'package:magic_pay_app/features/transfer/data/data_sources/remote_data_source.dart'
    as _i35;
import 'package:magic_pay_app/features/transfer/data/models/transfer_data_model.dart'
    as _i8;
import 'package:magic_pay_app/features/transfer/data/models/transfer_request_model.dart'
    as _i36;
import 'package:magic_pay_app/features/transfer/domain/entities/transfer_data.dart'
    as _i24;
import 'package:magic_pay_app/features/transfer/domain/entities/transfer_request.dart'
    as _i25;
import 'package:magic_pay_app/features/transfer/domain/repositories/transfer_repository.dart'
    as _i23;
import 'package:magic_pay_app/features/transfer/domain/usecases/transfer_complete.dart'
    as _i50;
import 'package:magic_pay_app/features/transfer/domain/usecases/transfer_confirm.dart'
    as _i49;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i37;
import 'package:shared_preferences/shared_preferences.dart' as _i51;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponseData_1 extends _i1.SmartFake implements _i3.ResponseData {
  _FakeResponseData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationDataModel_2 extends _i1.SmartFake
    implements _i4.NotificationDataModel {
  _FakeNotificationDataModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNotificationDetailModel_3 extends _i1.SmartFake
    implements _i5.NotificationDetailModel {
  _FakeNotificationDetailModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionsDataModel_4 extends _i1.SmartFake
    implements _i6.TransactionsDataModel {
  _FakeTransactionsDataModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransactionDetailModel_5 extends _i1.SmartFake
    implements _i7.TransactionDetailModel {
  _FakeTransactionDetailModel_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransferDataModel_6 extends _i1.SmartFake
    implements _i8.TransferDataModel {
  _FakeTransferDataModel_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanPayFormDataModel_7 extends _i1.SmartFake
    implements _i9.ScanPayFormDataModel {
  _FakeScanPayFormDataModel_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScanPayDataModel_8 extends _i1.SmartFake
    implements _i10.ScanPayDataModel {
  _FakeScanPayDataModel_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_9 extends _i1.SmartFake implements _i11.BaseOptions {
  _FakeBaseOptions_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_10 extends _i1.SmartFake
    implements _i11.HttpClientAdapter {
  _FakeHttpClientAdapter_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_11 extends _i1.SmartFake implements _i11.Transformer {
  _FakeTransformer_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_12 extends _i1.SmartFake implements _i11.Interceptors {
  _FakeInterceptors_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_13<T1> extends _i1.SmartFake implements _i11.Response<T1> {
  _FakeResponse_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> register(
          _i15.UserEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [user],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #register,
            [user],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> login({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #phone: phone,
            #password: password,
          },
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> logout() =>
      (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [HomeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepository extends _i1.Mock implements _i16.HomeRepository {
  MockHomeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> getProfile() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> updatePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [NotificationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRepository extends _i1.Mock
    implements _i17.NotificationRepository {
  MockNotificationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<
      _i2.Either<_i14.Failure, _i18.NotificationDataEntity>> getNotifications(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [page],
        ),
        returnValue: _i13.Future<
                _i2.Either<_i14.Failure, _i18.NotificationDataEntity>>.value(
            _FakeEither_0<_i14.Failure, _i18.NotificationDataEntity>(
          this,
          Invocation.method(
            #getNotifications,
            [page],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i18.NotificationDataEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i19.NotificationDetailEntity>>
      getNotificationDetail(String? notificationId) => (super.noSuchMethod(
            Invocation.method(
              #getNotificationDetail,
              [notificationId],
            ),
            returnValue: _i13.Future<
                    _i2
                    .Either<_i14.Failure, _i19.NotificationDetailEntity>>.value(
                _FakeEither_0<_i14.Failure, _i19.NotificationDetailEntity>(
              this,
              Invocation.method(
                #getNotificationDetail,
                [notificationId],
              ),
            )),
          ) as _i13
              .Future<_i2.Either<_i14.Failure, _i19.NotificationDetailEntity>>);
}

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i20.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<
      _i2.Either<_i14.Failure, _i21.TransactionsDataEntity>> getTransactions(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [page],
        ),
        returnValue: _i13.Future<
                _i2.Either<_i14.Failure, _i21.TransactionsDataEntity>>.value(
            _FakeEither_0<_i14.Failure, _i21.TransactionsDataEntity>(
          this,
          Invocation.method(
            #getTransactions,
            [page],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i21.TransactionsDataEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i22.TransactionDetailEntity>>
      getTransactionDetail(String? transactionId) => (super.noSuchMethod(
            Invocation.method(
              #getTransactionDetail,
              [transactionId],
            ),
            returnValue: _i13.Future<
                    _i2
                    .Either<_i14.Failure, _i22.TransactionDetailEntity>>.value(
                _FakeEither_0<_i14.Failure, _i22.TransactionDetailEntity>(
              this,
              Invocation.method(
                #getTransactionDetail,
                [transactionId],
              ),
            )),
          ) as _i13
              .Future<_i2.Either<_i14.Failure, _i22.TransactionDetailEntity>>);
}

/// A class which mocks [TransferRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferRepository extends _i1.Mock
    implements _i23.TransferRepository {
  MockTransferRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i24.TransferDataEntity>>
      transferConfirm(_i25.TransferRequestEntity? transferRequest) =>
          (super.noSuchMethod(
            Invocation.method(
              #transferConfirm,
              [transferRequest],
            ),
            returnValue: _i13.Future<
                    _i2.Either<_i14.Failure, _i24.TransferDataEntity>>.value(
                _FakeEither_0<_i14.Failure, _i24.TransferDataEntity>(
              this,
              Invocation.method(
                #transferConfirm,
                [transferRequest],
              ),
            )),
          ) as _i13.Future<_i2.Either<_i14.Failure, _i24.TransferDataEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, String>> transferComplete(
          _i25.TransferRequestEntity? transferRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferComplete,
          [transferRequest],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, String>>.value(
            _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #transferComplete,
            [transferRequest],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, String>>);
}

/// A class which mocks [ScanPayRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanPayRepository extends _i1.Mock implements _i26.ScanPayRepository {
  MockScanPayRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i27.ScanPayFormDataEntity>> scanQrCode(
          String? toPhone) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanQrCode,
          [toPhone],
        ),
        returnValue: _i13
            .Future<_i2.Either<_i14.Failure, _i27.ScanPayFormDataEntity>>.value(
            _FakeEither_0<_i14.Failure, _i27.ScanPayFormDataEntity>(
          this,
          Invocation.method(
            #scanQrCode,
            [toPhone],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i27.ScanPayFormDataEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i28.ScanPayDataEntity>> payConfirm(
          _i29.ScanPayRequestEntity? scanPayRequestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #payConfirm,
          [scanPayRequestEntity],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i28.ScanPayDataEntity>>.value(
                _FakeEither_0<_i14.Failure, _i28.ScanPayDataEntity>(
          this,
          Invocation.method(
            #payConfirm,
            [scanPayRequestEntity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i28.ScanPayDataEntity>>);

  @override
  _i13.Future<_i2.Either<_i14.Failure, String>> payComplete(
          _i29.ScanPayRequestEntity? scanPayRequestEntity) =>
      (super.noSuchMethod(
        Invocation.method(
          #payComplete,
          [scanPayRequestEntity],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, String>>.value(
            _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #payComplete,
            [scanPayRequestEntity],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, String>>);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i30.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.ResponseData> register(_i31.UserModel? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [user],
        ),
        returnValue: _i13.Future<_i3.ResponseData>.value(_FakeResponseData_1(
          this,
          Invocation.method(
            #register,
            [user],
          ),
        )),
      ) as _i13.Future<_i3.ResponseData>);

  @override
  _i13.Future<_i3.ResponseData> login({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #phone: phone,
            #password: password,
          },
        ),
        returnValue: _i13.Future<_i3.ResponseData>.value(_FakeResponseData_1(
          this,
          Invocation.method(
            #login,
            [],
            {
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i13.Future<_i3.ResponseData>);

  @override
  _i13.Future<_i3.ResponseData> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i13.Future<_i3.ResponseData>.value(_FakeResponseData_1(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i13.Future<_i3.ResponseData>);
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i32.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i3.ResponseData> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i13.Future<_i3.ResponseData>.value(_FakeResponseData_1(
          this,
          Invocation.method(
            #getProfile,
            [],
          ),
        )),
      ) as _i13.Future<_i3.ResponseData>);

  @override
  _i13.Future<_i3.ResponseData> updatePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i13.Future<_i3.ResponseData>.value(_FakeResponseData_1(
          this,
          Invocation.method(
            #updatePassword,
            [],
            {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i13.Future<_i3.ResponseData>);
}

/// A class which mocks [NotificationRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationRemoteDataSource extends _i1.Mock
    implements _i33.NotificationRemoteDataSource {
  MockNotificationRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i4.NotificationDataModel> getNotifications(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotifications,
          [page],
        ),
        returnValue: _i13.Future<_i4.NotificationDataModel>.value(
            _FakeNotificationDataModel_2(
          this,
          Invocation.method(
            #getNotifications,
            [page],
          ),
        )),
      ) as _i13.Future<_i4.NotificationDataModel>);

  @override
  _i13.Future<_i5.NotificationDetailModel> getNotificationDetail(
          String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNotificationDetail,
          [notificationId],
        ),
        returnValue: _i13.Future<_i5.NotificationDetailModel>.value(
            _FakeNotificationDetailModel_3(
          this,
          Invocation.method(
            #getNotificationDetail,
            [notificationId],
          ),
        )),
      ) as _i13.Future<_i5.NotificationDetailModel>);
}

/// A class which mocks [TransactionRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRemoteDataSource extends _i1.Mock
    implements _i34.TransactionRemoteDataSource {
  MockTransactionRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i6.TransactionsDataModel> getTransactions(int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactions,
          [page],
        ),
        returnValue: _i13.Future<_i6.TransactionsDataModel>.value(
            _FakeTransactionsDataModel_4(
          this,
          Invocation.method(
            #getTransactions,
            [page],
          ),
        )),
      ) as _i13.Future<_i6.TransactionsDataModel>);

  @override
  _i13.Future<_i7.TransactionDetailModel> getTransactionDetail(
          String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionDetail,
          [transactionId],
        ),
        returnValue: _i13.Future<_i7.TransactionDetailModel>.value(
            _FakeTransactionDetailModel_5(
          this,
          Invocation.method(
            #getTransactionDetail,
            [transactionId],
          ),
        )),
      ) as _i13.Future<_i7.TransactionDetailModel>);
}

/// A class which mocks [TransferRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferRemoteDataSource extends _i1.Mock
    implements _i35.TransferRemoteDataSource {
  MockTransferRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i8.TransferDataModel> transferConfirm(
          _i36.TransferRequestModel? transferRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferConfirm,
          [transferRequestModel],
        ),
        returnValue:
            _i13.Future<_i8.TransferDataModel>.value(_FakeTransferDataModel_6(
          this,
          Invocation.method(
            #transferConfirm,
            [transferRequestModel],
          ),
        )),
      ) as _i13.Future<_i8.TransferDataModel>);

  @override
  _i13.Future<String> transferComplete(
          _i36.TransferRequestModel? transferRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #transferComplete,
          [transferRequestModel],
        ),
        returnValue: _i13.Future<String>.value(_i37.dummyValue<String>(
          this,
          Invocation.method(
            #transferComplete,
            [transferRequestModel],
          ),
        )),
      ) as _i13.Future<String>);
}

/// A class which mocks [ScanPayRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanPayRemoteDataSource extends _i1.Mock
    implements _i38.ScanPayRemoteDataSource {
  MockScanPayRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i9.ScanPayFormDataModel> scanQrCode(String? toPhone) =>
      (super.noSuchMethod(
        Invocation.method(
          #scanQrCode,
          [toPhone],
        ),
        returnValue: _i13.Future<_i9.ScanPayFormDataModel>.value(
            _FakeScanPayFormDataModel_7(
          this,
          Invocation.method(
            #scanQrCode,
            [toPhone],
          ),
        )),
      ) as _i13.Future<_i9.ScanPayFormDataModel>);

  @override
  _i13.Future<_i10.ScanPayDataModel> payConfirm(
          _i39.ScanPayRequestModel? scanPayRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #payConfirm,
          [scanPayRequestModel],
        ),
        returnValue:
            _i13.Future<_i10.ScanPayDataModel>.value(_FakeScanPayDataModel_8(
          this,
          Invocation.method(
            #payConfirm,
            [scanPayRequestModel],
          ),
        )),
      ) as _i13.Future<_i10.ScanPayDataModel>);

  @override
  _i13.Future<String> payComplete(
          _i39.ScanPayRequestModel? scanPayRequestModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #payComplete,
          [scanPayRequestModel],
        ),
        returnValue: _i13.Future<String>.value(_i37.dummyValue<String>(
          this,
          Invocation.method(
            #payComplete,
            [scanPayRequestModel],
          ),
        )),
      ) as _i13.Future<String>);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i40.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> execute({
    required String? phone,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #phone: phone,
            #password: password,
          },
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #phone: phone,
              #password: password,
            },
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i41.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [RegisterUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRegisterUseCase extends _i1.Mock implements _i42.RegisterUseCase {
  MockRegisterUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> execute(
          _i15.UserEntity? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [user],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #execute,
            [user],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i43.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> execute() =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #execute,
            [],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [UpdatePasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePasswordUseCase extends _i1.Mock
    implements _i44.UpdatePasswordUseCase {
  MockUpdatePasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>> execute({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue:
            _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>.value(
                _FakeEither_0<_i14.Failure, _i3.ResponseData>(
          this,
          Invocation.method(
            #execute,
            [],
            {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i3.ResponseData>>);
}

/// A class which mocks [GetNotificationsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotificationsUseCase extends _i1.Mock
    implements _i45.GetNotificationsUseCase {
  MockGetNotificationsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i18.NotificationDataEntity>> execute(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [page],
        ),
        returnValue: _i13.Future<
                _i2.Either<_i14.Failure, _i18.NotificationDataEntity>>.value(
            _FakeEither_0<_i14.Failure, _i18.NotificationDataEntity>(
          this,
          Invocation.method(
            #execute,
            [page],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i18.NotificationDataEntity>>);
}

/// A class which mocks [GetNotificationDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNotificationDetailUseCase extends _i1.Mock
    implements _i46.GetNotificationDetailUseCase {
  MockGetNotificationDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i19.NotificationDetailEntity>> execute(
          String? notificationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [notificationId],
        ),
        returnValue: _i13.Future<
                _i2.Either<_i14.Failure, _i19.NotificationDetailEntity>>.value(
            _FakeEither_0<_i14.Failure, _i19.NotificationDetailEntity>(
          this,
          Invocation.method(
            #execute,
            [notificationId],
          ),
        )),
      ) as _i13
          .Future<_i2.Either<_i14.Failure, _i19.NotificationDetailEntity>>);
}

/// A class which mocks [GetTransactionsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTransactionsUseCase extends _i1.Mock
    implements _i47.GetTransactionsUseCase {
  MockGetTransactionsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i21.TransactionsDataEntity>> execute(
          int? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [page],
        ),
        returnValue: _i13.Future<
                _i2.Either<_i14.Failure, _i21.TransactionsDataEntity>>.value(
            _FakeEither_0<_i14.Failure, _i21.TransactionsDataEntity>(
          this,
          Invocation.method(
            #execute,
            [page],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i21.TransactionsDataEntity>>);
}

/// A class which mocks [GetTransactionDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTransactionDetailUseCase extends _i1.Mock
    implements _i48.GetTransactionDetailUseCase {
  MockGetTransactionDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i22.TransactionDetailEntity>> execute(
          String? transactionId) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [transactionId],
        ),
        returnValue: _i13.Future<
                _i2.Either<_i14.Failure, _i22.TransactionDetailEntity>>.value(
            _FakeEither_0<_i14.Failure, _i22.TransactionDetailEntity>(
          this,
          Invocation.method(
            #execute,
            [transactionId],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i22.TransactionDetailEntity>>);
}

/// A class which mocks [TransferConfirmUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferConfirmUseCase extends _i1.Mock
    implements _i49.TransferConfirmUseCase {
  MockTransferConfirmUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, _i24.TransferDataEntity>> execute(
          _i25.TransferRequestEntity? transferRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [transferRequest],
        ),
        returnValue: _i13
            .Future<_i2.Either<_i14.Failure, _i24.TransferDataEntity>>.value(
            _FakeEither_0<_i14.Failure, _i24.TransferDataEntity>(
          this,
          Invocation.method(
            #execute,
            [transferRequest],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, _i24.TransferDataEntity>>);
}

/// A class which mocks [TransferCompleteUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransferCompleteUseCase extends _i1.Mock
    implements _i50.TransferCompleteUseCase {
  MockTransferCompleteUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.Future<_i2.Either<_i14.Failure, String>> execute(
          _i25.TransferRequestEntity? transferRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #execute,
          [transferRequest],
        ),
        returnValue: _i13.Future<_i2.Either<_i14.Failure, String>>.value(
            _FakeEither_0<_i14.Failure, String>(
          this,
          Invocation.method(
            #execute,
            [transferRequest],
          ),
        )),
      ) as _i13.Future<_i2.Either<_i14.Failure, String>>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i51.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(Invocation.method(
        #get,
        [key],
      )) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(Invocation.method(
        #getBool,
        [key],
      )) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(Invocation.method(
        #getInt,
        [key],
      )) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(Invocation.method(
        #getDouble,
        [key],
      )) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(Invocation.method(
        #getString,
        [key],
      )) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(
        #getStringList,
        [key],
      )) as List<String>?);

  @override
  _i13.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i13.Future<void>.value(),
        returnValueForMissingStub: _i13.Future<void>.value(),
      ) as _i13.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i11.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_9(
          this,
          Invocation.getter(#options),
        ),
      ) as _i11.BaseOptions);

  @override
  set options(_i11.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_10(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i11.HttpClientAdapter);

  @override
  set httpClientAdapter(_i11.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_11(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i11.Transformer);

  @override
  set transformer(_i11.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_12(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i11.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i13.Future<_i11.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i11.Options? options,
    _i11.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i11.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i11.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i11.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i13.Future<_i11.Response<dynamic>>.value(_FakeResponse_13<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<dynamic>>);

  @override
  _i13.Future<_i11.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i11.ProgressCallback? onReceiveProgress,
    _i11.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i11.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i13.Future<_i11.Response<dynamic>>.value(_FakeResponse_13<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<dynamic>>);

  @override
  _i13.Future<_i11.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i11.CancelToken? cancelToken,
    _i11.Options? options,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i11.CancelToken? cancelToken,
    _i11.Options? options,
    _i11.ProgressCallback? onSendProgress,
    _i11.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);

  @override
  _i13.Future<_i11.Response<T>> fetch<T>(_i11.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i13.Future<_i11.Response<T>>.value(_FakeResponse_13<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i13.Future<_i11.Response<T>>);
}
